<?php
/**
 * Created by PhpStorm.
 * User: CTAC
 * Date: 11.03.2019
 * Time: 12:11
 */

namespace App\InsuranceAPI\Liberty;

class LibertyDirect
{
    private static $libertyCurrency = [
        'EUR' => 14,
        'USD' => 1,
        'RUB' => 0
    ];

    public static function getCurrencyUID($currency)
    {
        return self::$libertyCurrency[$currency] ?? 14;
    }

    private static $libertyCountry = [
        'CARIBBEAN' => 244,
        'SCHENGEN' => 242,
        'ABKHAZIA' => 240,
        'AUSTRALIA' => 12,
        'AUSTRIA' => 13,
        'AZERBAIJAN' => 10,
        'ALBANIA' => 3,
        'ALGERIA' => 5,
        'ANGOLA' => 8,
        'ANDORRA' => 7,
        'ANTIGUA' => 9,
        'ARGENTINA' => 11,
        'ARMENIA' => 17,
        'AFGANISTAN' => 2,
        'BAHAMAS' => 14,
        'BANGLADESH' => 16,
        'BARBADOS' => 18,
        'BAHRAIN' => 15,
        'BELIZE' => 27,
        'BELORUSSIA' => 35,
        'BELGIUM' => 19,
        'BENIN' => 59,
        'BERMUDAS' => 20,
        'BULGARIA' => 32,
        'BOLIVIA' => 22,
        'BOSNIA' => 23,
        'BOTSVANA' => 24,
        'BRAZIL' => 26,
        'BRUNEI' => 31,
        'BURUNDI' => 34,
        'BHUTAN' => 21,
        'VATICAN' => 95,
        'BRITAIN' => 224,
        'HUNGARY' => 98,
        'VENEZUELA' => 231,
        'VIETNAM' => 194,
        'HAITI' => 93,
        'GYANA' => 92,
        'GUADELOUPE' => 88,
        'GUATEMALA' => 90,
        'GUIANA' => 74,
        'GERMANY' => 81,
        'GIBRALTAR' => 83,
        'HONDURAS' => 96,
        'GRENADA' => 87,
        'GREENLAND' => 86,
        'GREECE' => 85,
        'GEORGIA' => 79,
        'GUAM' => 89,
        'DENMARK' => 60,
        'DOMINICA' => 61,
        'DOMINICAN' => 62,
        'EGYPT' => 223,
        'ZAMBIA' => 238,
        'ZIMBABWE' => 198,
        'ISRAEL' => 105,
        'INDIA' => 100,
        'INDONESIA' => 101,
        'JORDAN' => 111,
        'IRAQ' => 103,
        'IRAN' => 102,
        'IRELAND' => 104,
        'ICELAND' => 99,
        'SPAIN' => 199,
        'ITALY' => 106,
        'YEMEN' => 234,
        'CABO VERDE' => 39,
        'KAZAKHSTAN' => 110,
        'CAYMAN' => 40,
        'CAMBODIA' => 36,
        'CAMEROON' => 37,
        'CANADA' => 38,
        'KENYA' => 112,
        'CYPRUS' => 57,
        'KYRGYZSTAN' => 116,
        'CHINA' => 45,
        'COCOS' => 48,
        'COLOMBIA' => 49,
        'COMORO' => 50,
        'CONGO' => 51,
        'COSTA' => 54,
        'KUWAIT' => 115,
        'LAO' => 117,
        'LATVIA' => 120,
        'LEBANON' => 118,
        'LITHUANIA' => 124,
        'LIECHTENSTEIN' => 123,
        'LUXEMBOURG' => 125,
        'MAURITIUS' => 135,
        'MAURITANIA' => 134,
        'MADAGASCAR' => 127,
        'MALAYSIA' => 129,
        'MALI' => 131,
        'MALDIVES' => 130,
        'MALTA' => 132,
        'MOROCCO' => 141,
        'MEXICO' => 136,
        'MOZAMBIQUE' => 142,
        'MOLDOVA' => 139,
        'MONACO' => 137,
        'MONGOLIA' => 138,
        'MYANMAR' => 33,
        'NAMIBIA' => 144,
        'NAURU' => 145,
        'NEPAL' => 146,
        'NIGER' => 154,
        'NIGERIA' => 155,
        'NETHERLAND' => 147,
        'NICARAGUA' => 153,
        'ZEALAND' => 152,
        'NORWAY' => 158,
        'UAE' => 214,
        'OMAN' => 143,
        'COOK' => 53,
        'PAKISTAN' => 164,
        'PANAMA' => 165,
        'PAPUA' => 166,
        'PARAGUAY' => 167,
        'PERU' => 168,
        'POLAND' => 171,
        'PORTUGAL' => 172,
        'PUERTO' => 175,
        'RUSSIA' => 1,
        'ROMANIA' => 178,
        'USA' => 226,
        'SALVADOR' => 64,
        'ARABIA' => 188,
        'SEYCHELLES' => 190,
        'SENEGAL' => 189,
        'SERBIA' => 241,
        'SINGAPORE' => 192,
        'SYRIA' => 207,
        'SLOVAKIA' => 193,
        'SLOVENIA' => 195,
        'SOLOMON' => 29,
        'SOMALIA' => 196,
        'SUDAN' => 201,
        'TADJIKISTAN' => 208,
        'THAILAND' => 209,
        'TAIWAN' => 46,
        'TANSANIA' => 225,
        'TRINIDAD' => 213,
        'TUNISIA' => 215,
        'TURKMENISTAN' => 217,
        'TURKEY' => 216,
        'UGANDA' => 220,
        'UZBEKISTAN' => 230,
        'UKRAINE' => 221,
        'URUGUAY' => 229,
        'FAEROES' => 69,
        'FIJI' => 71,
        'PHILIPPINES' => 169,
        'FRANCE' => 73,
        'HEARD' => 94,
        'CROATIA' => 55,
        'CAR' => 41,
        'CHAD' => 43,
        'CZECH' => 58,
        'SWITZERLAND' => 206,
        'SWEDEN' => 205,
        'SRILANKA' => 42,
        'ECUADOR' => 63,
        'GUINEA' => 65,
        'ESTONIA' => 68,
        'ETHIOPIA' => 66,
        'SAFRICA' => 197,
        'KOREA' => 114,
        'JAMAICA' => 108,
        'JAPAN' => 109
    ];

    public static function getCountryUID($country)
    {
        return self::$libertyCountry[$country] ?? false;
    }
}